sudo: false
language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
before_install:
  - ! [[ $(node -v) =~ ^v9.*$ ]] && npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
